graphql-python/graphql-server

- graphql_server/__init__.py
`HttpQueryError` not part of `__all__` is a breaking change to libraries like `sanic-graphql` who rely on importing it:
https://github.com/graphql-python/sanic-graphql/blob/master/sanic_graphql/graphqlview.py#L12
> Expose `HttpQueryError` in `__all__`

- graphql_server/error.py
As stated in the documentation for [`__hash__()`](https://docs.python.org/3.5/reference/datamodel.html#object.__hash__) method in Python 3, if class overrides `__eq__()` but doesn't define `__hash__()`, this will implicitely be set to `None`. This is the case of `HttpQueryError` exception class. This causes issues for logging, particularly `traceback` module which raises `TypeError: unhashable type: 'HttpQueryError'`.
Consider this minimal example:
```
import logging
from graphql_server import HttpQueryError
logger = logging.getLogger(__name__)
try:
raise HttpQueryError(400, 'Error')
except HttpQueryError as e:
logger.exception(e)
```
This results in:
```
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
msg = …
```
> Make HttpQueryError hashable

- .gitignore
- .travis.yml
- README.md
- README.rst
- bin/build_docs
- bin/convert_documentation
- bin/convert_readme
- graphql_server/__init__.py
- graphql_server/error.py
- setup.cfg
- setup.py
- tox.ini
Separate between official and internal helper functions. Only the official functions are listed in `__all__`, and the internal ones are moved to the bottom of the file.
Use `json_encode` and `default_format_error` as default values, so they don't need to be imported any more (and have therefore been excluded from `__all__`.  But everything that is now considered internal is still available for import, nothing is broken.
Also, added a script to create docs from the docstrings.
> Improve README and add docstrings

- graphql_server/__init__.py
- tests/test_asyncio.py
- tests/test_query.py
- tests/utils.py
- tox.ini
> Don't use executor in run_http_query when return_promise=True

- graphql_server/flask/graphqlview.py
Missed this in the review but executor is no longer a supported feature of graphql-core.
> Remove references to executor in Flask view

- graphql_server/__init__.py
- setup.py
- tests/flask/test_graphqlview.py
- tests/test_helpers.py
- tests/test_query.py
This PR modifies the logic that determines the HTTP status code to follow the v2 behaviour (see https://github.com/graphql-python/graphql-server-core/pull/36#discussion_r407592638). A HTTP 400 response should only be returned only when the errors are not specific to a particular part of the query (a validation error for example) otherwise a HTTP 200 response should be returned.
> Return 200 errors

- graphql_server/sanic/__init__.py
- graphql_server/sanic/graphqlview.py
- graphql_server/sanic/render_graphiql.py
- setup.cfg
- setup.py
- tests/sanic/app.py
- tests/sanic/schema.py
- tests/sanic/test_graphiqlview.py
- tests/sanic/test_graphqlview.py
References #34, this PR merges `sanic-graphql` library into `graphql-server-core`.
To install the integration with sanic, run the below command on your terminal.
`pip install graphql-server-core[sanic]`
~**NOTE** The only main issue so far is dealing with the asyncio executor tests.~
> Merge sanic-graphql 

- .gitignore
- graphql_server/__init__.py
This is a preliminary fix for #43. As final fix should refactor to use `execute` instead of `graphql/graphql_sync` in order to separate the validation from the execution.
> Run additional parse step only when necessary (#43)

- graphql_server/__init__.py
- graphql_server/version.py
- setup.py
- tests/__init__.py
- tests/test_version.py
Fixes #47 based on graphql-core logic to handle package version.
> Expose version number as __version__

- graphql_server/__init__.py
- tests/test_query.py
Instead of graphql()/graphql_sync() we now call execute() directly.
This solves not only #43 but also allows adding custom validation rules and limiting the number of reported errors.
> Split parsing, validation and execution (#43)

- MANIFEST.in
- README.md
- docs/aiohttp.md
- docs/flask.md
- docs/sanic.md
- docs/webob.md
- graphql_server/flask/graphqlview.py
- graphql_server/sanic/graphqlview.py
- graphql_server/webob/graphqlview.py
This pull request fixes #46. Be aware that several options are being added on #55, like as the `GraphiQLOptions` or Flask context (which was missing).
~This is a initial draft of how integration docs would be, in this case, I started with Flask to checkout what else should I put at the other docs, so **do not merge yet**.~
> Docs about integration with each framework

- graphql_server/aiohttp/graphqlview.py
- graphql_server/flask/graphqlview.py
- graphql_server/render_graphiql.py
- graphql_server/sanic/graphqlview.py
- graphql_server/webob/graphqlview.py
- tests/aiohttp/schema.py
- tests/aiohttp/test_graphqlview.py
- tests/flask/schema.py
- tests/flask/test_graphqlview.py
- tests/sanic/schema.py
- tests/sanic/test_graphqlview.py
- tests/webob/schema.py
- tests/webob/test_graphqlview.py
This add support for graphiql options like as:
* `default_query`: An optional GraphQL string to use when no query is provided and no stored query exists from a previous session. If not provided, GraphiQL will use its own default query.
* `header_editor_enabled`: An optional boolean which enables the header editor when true. Defaults to **false**.
* `should_persist_headers`:  An optional boolean which enables to persist headers to storage when true. Defaults to **false**.
Also, add the missing `context` attribute as requested at this old [flask-graphql#52](https://github.com/graphql-python/flask-graphql/issues/52) issue.
However, the approach I used for all 4 servers (flask, aiohttp, webob, sanic) was based on this [sanic#8](https://github.com/graphql-python/sanic-graphql/issues/8) issue …
> Add graphiql options and missing flask context

- CONTRIBUTING.md
- README.md
- docs/aiohttp.md
- docs/flask.md
- docs/sanic.md
- docs/webob.md
- graphql_server/__init__.py
- graphql_server/version.py
- setup.py
This is it! 🚀 Last step to publish graphql-server v3 as beta release 🍰
> chore: rename to graphql-server and bump version

- README.md
A quick fix on the readme links.
> docs: update links on readme

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- Enable GH Actions on push
- Submit coverage report to codecov
- Add Windows to OS tests matrix
> chore: submit coverage to codecov

- README.md
- graphql_server/aiohttp/graphqlview.py
- graphql_server/sanic/graphqlview.py
- tests/aiohttp/schema.py
- tests/aiohttp/test_graphiqlview.py
- tests/sanic/schema.py
- tests/sanic/test_graphiqlview.py
Resolves https://github.com/graphql-python/graphql-server/issues/64 using the fix suggested by ketanbshah.
I admit that I am not positive the fix is required for sanic, but it should not hurt, and the original code was identical.
> Fix enable_async for aiohttp and sanic

- graphql_server/aiohttp/graphqlview.py
- graphql_server/quart/__init__.py
- graphql_server/quart/graphqlview.py
- setup.py
- tests/flask/test_graphqlview.py
- tests/quart/app.py
- tests/quart/schema.py
- tests/quart/test_graphiqlview.py
- tests/quart/test_graphqlview.py
Fixes #68.
**TODO** 
- Include in documentation, see #61 
- Fix the last missing test on `test_graphqlview.py` regarding file handling. Looks like this is not supported at the moment, see https://gitlab.com/pgjones/quart/-/issues/147
> feat: Quart Server Integration

- setup.py
`pip install` and `python setup.py build` also installed the `tests` directory to the environment. I'm not sure about what the best fix is, but this seems to do the trick and [has also been suggested on the internet](https://discuss.python.org/t/excluding-a-package-from-a-wheel-install/861/3).
Example output before the fix, showing the error:
```shell script
$ mkdir foo && pip install . --target foo && ls -l foo  # installing to venv (without --target) had the same problem
... output from pip ...
drwxr-xr-x  3 user user    96 Nov 25 22:25 __pycache__/
drwxr-xr-x 15 user user   480 Nov 25 22:25 graphql/
drwxr-xr-x  8 user user   256 Nov 25 22:25 graphql_core-3.1.2.dist-info/
drwxr-xr-x 12 user user   384 Nov 25 22:25 graphql_server/
drwxr-xr-x  9 user user   288 Nov 25 22:25 …
```
> Prevent including test directory when installing package

- docs/aiohttp.md
- docs/flask.md
- docs/sanic.md
- docs/webob.md
Supersede #90.
Thanks to 476edf370099df050289f9c0b8d70007e7dc8ecc users can pass a `schema` object of type `graphene.Schema` to `GraphQLView` directly. This is equivalent to passing `schema.graphql_schema`
> docs: add docs on integration with Graphene v3

- graphql_server/aiohttp/graphqlview.py
- graphql_server/quart/graphqlview.py
- graphql_server/sanic/graphqlview.py
- graphql_server/utils.py
- setup.py
- tests/quart/app.py
- tests/quart/schema.py
- tests/quart/test_graphqlview.py
Gather execution results asynchronously instead of awaiting them one by one.
> chore: asynchronously gather execution results

- graphql_server/aiohttp/graphqlview.py
- graphql_server/flask/graphqlview.py
- graphql_server/quart/graphqlview.py
- graphql_server/sanic/graphqlview.py
- graphql_server/webob/graphqlview.py
- tests/aiohttp/schema.py
- tests/aiohttp/test_graphqlview.py
- tests/flask/schema.py
- tests/flask/test_graphqlview.py
- tests/quart/schema.py
- tests/quart/test_graphqlview.py
- tests/sanic/schema.py
- tests/sanic/test_graphqlview.py
- tests/webob/schema.py
- tests/webob/test_graphqlview.py
From PEP-8: "beware of writing if x when you really mean if x is not None – e.g. when testing whether a variable or argument that defaults to None was set to some other value. The other value might have a type (such as a container) that could be false in a boolean context!"
Currently a custom MutableMapping cannot be used as a graphql context if it is passed to GraphQLView empty
> Allow empty custom context in GraphQLView

- .github/workflows/deploy.yml
Update the `pypa/gh-action-pypi-publish` github action to use the latest v1. We're using `v1.1.0` that's 3 years old. The current one is `v1.8.5`. Nothing else needs updating according to the doc.
> Update pypi publishing github action

- graphql_server/channels/graphql_transport_ws.py
- graphql_server/websockets/transport_ws_protocol/handlers.py
- graphql_server/websockets/transport_ws_protocol/types.py
I am guessing the `v3` branch was only used with `GraphQLWSHandler`, and not with `GraphQLTransportWSHandler`. That's probably why there were a bunch of bugs. This PR fixes the errors I got when trying to use subscriptions with the `graphql-transport-ws` protocol.
The first error I got was
```
Can't instantiate abstract class GraphQLTransportWSHandler with abstract method send_xjson
```
I implemented this function and the error went away.
Second error was with message types - they were `TypedDict`s, but typeddicts are essentially dicts.
This means additional fields specified are not properly used. I fixed it by converting them to `dataclasses` and adding a `to_dict` field to it.
> Fix bugs with transport-ws-protocol

- .pre-commit-config.yaml
- graphql_server/version.py
- setup.py
- tests/test_version.py
Fix `VersionInfo` and `test_version.py` to handle release candidates correctly. Also refactor the tests.
> refactor!: Drop VersionInfo in favor of tuple

- .pre-commit-config.yaml
- .ruff.toml
- tests/aiohttp/test_graphiqlview.py
- tests/flask/test_graphiqlview.py
- tests/quart/test_graphiqlview.py
- tests/sanic/test_graphiqlview.py
- tests/webob/test_graphiqlview.py
ruff formatter (black-compatible code formatter built in ruff) is out of beta https://astral.sh/blog/the-ruff-formatter.
> chore: replace black with ruff formatter
